version: "3.1"
services:
  mongodb:
    profiles: ["mongodb"] # deactivate by default
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  backend:
    build: backend
    volumes:
      - ./backend:/backend/
    command: npm run start
    ports:
      - "8080:8080"
volumes:
  data:
